
remote_theme: just-the-docs/just-the-docs
  
title: 永冬泩
description: 记录从生活中走出的文字
search_enabled: true

# Google Analytics (GA4 or Universal Analytics)
google_analytics:
  id: "G-VRVZ2V504Z"   # your GA4 Measurement ID
  # or for Universal Analytics:
  # id: "UA-XXXXXXXXX-X"

plugins:
  - jekyll-last-modified-at
# Footer last edited timestamp
last_edit_timestamp: true
last_edit_time_format: "%b %e %Y at %I:%M %p"
