
# this was tried but doesn't work for html, not convenient
# all files are in /docs
site_name: 海泩文字集
site_url: https://haishion7.github.io
theme:
  name: material
  language: zh  # Enables Chinese UI and search
plugins:
  - search:
      lang: zh  # Activates Jieba for Chinese tokenization
plugins:
  - search
  - include_dir_to_nav

nav:
  - Home: index.md
  - 散文: 散文/     # Auto-scans .md + .html recursively!
  - Reference: ref/
