site_name: 海泩文字集
site_url: https://haishion7.github.io
theme:
  name: material
  language: zh  # Enables Chinese UI and search
plugins:
  - search:
      lang: zh  # Activates Jieba for Chinese tokenization
nav:
  - Home: index.md
